program_param:
  wandb_key: b41fa9bf3a38422dafc16e253d84694489607e9f
  project_name: jigsaw
  seed: 42

data_param:
  dir_name: jigsaw_toxic_severity_rating
  train_file_name: validation_data.csv
  infer_file_name: comments_to_score.csv

model_param:
  model_name: unbiased
  max_length: 128
  scheduler: cos_ann
  mix_precision: True
  num_classes: 1
  device: cuda

train_param:
  epochs: 5
  lr: 1e-4  # 2e-5
  min_lr: 1e-6
  weight_decay: 1e-6  # 0.01
  num_folds: 5
  accumulate_grad_batches: 2
  ranking_margin: 0.5
  batch_size: 16
  T_max: 500
  T_0: 50
  save_dir: checkpoint/unbiased
  loss: margin_ranking_loss
  num_workers: 2
  shuffle: True
  pin_memory: True
  drop_last: True

valid_param:
  batch_size: 64
  num_workers: 2
  shuffle: False
  pin_memory: True

infer_param:
  batch_size: 64
  num_workers: 2
  shuffle: False
  pin_memory: True
  checkpoint_path: checkpoint/unbiased/unbiased.bin
  save_dir: /Users/ympai/kgl/jigsaw/toxic_severity/jigsaw-rate-severity-of-toxic-comments/output/unbiased